# Generated by Django 2.0.4 on 2019-07-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Back',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VIN', models.CharField(max_length=32, verbose_name='VIN号')),
                ('longitude', models.CharField(max_length=32, verbose_name='经度')),
                ('latitude', models.CharField(max_length=32, verbose_name='纬度')),
                ('create_time', models.DateTimeField(verbose_name='添加数据时间')),
            ],
            options={
                'db_table': 'back',
            },
        ),
    ]
