# Generated by Django 2.2.2 on 2019-07-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=64, verbose_name='路由')),
                ('title', models.CharField(max_length=32, verbose_name='路由名称')),
            ],
            options={
                'db_table': 'permission',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolename', models.CharField(max_length=32, verbose_name='角色名')),
                ('permissions', models.ManyToManyField(to='user.Permission', verbose_name='角色权限')),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('pwd', models.CharField(max_length=32, verbose_name='密码')),
                ('phone', models.IntegerField(null=True, unique=True, verbose_name='用户手机号码')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='自动创建当前保存的时间')),
                ('roles', models.ManyToManyField(to='user.Role', verbose_name='角色')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
