# Generated by Django 2.0.4 on 2019-07-23 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VIN', models.CharField(max_length=32, unique=True, verbose_name='VIN号')),
                ('car_num', models.CharField(max_length=16, null=True, verbose_name='车牌号')),
                ('ICCID', models.CharField(max_length=32, null=True, verbose_name='ICCID号')),
                ('driver', models.CharField(max_length=8, null=True, verbose_name='司机')),
                ('dept', models.CharField(max_length=16, null=True, verbose_name='部门')),
                ('version', models.CharField(max_length=32, null=True, verbose_name='版本号')),
                ('status', models.IntegerField(default=0, null=True, verbose_name='状态')),
                ('ip', models.CharField(max_length=512, null=True, verbose_name='升级文件传输地址')),
                ('ftp', models.CharField(max_length=32, null=True, verbose_name='用户名')),
                ('pwd', models.CharField(max_length=32, null=True, verbose_name='密码')),
                ('create_time', models.DateTimeField(auto_now=True, null=True, verbose_name='添加数据时间')),
            ],
            options={
                'db_table': 'car',
            },
        ),
        migrations.CreateModel(
            name='CaseFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='car', verbose_name='保存文件路径')),
            ],
            options={
                'db_table': 'case_file',
            },
        ),
    ]
