# Generated by Django 2.0.4 on 2019-11-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VIN', models.CharField(max_length=32, unique=True, verbose_name='VIN号')),
                ('longitude', models.CharField(max_length=32, verbose_name='经度')),
                ('latitude', models.CharField(max_length=32, verbose_name='纬度')),
                ('type', models.CharField(max_length=32, null=True, verbose_name='类别')),
                ('create_time', models.DateTimeField(auto_now=True, null=True, verbose_name='添加数据时间')),
                ('spare_1', models.CharField(max_length=128, null=True, verbose_name='备用1')),
                ('spare_2', models.CharField(max_length=128, null=True, verbose_name='备用2')),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
