# Generated by Django 2.0.4 on 2019-09-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ICCID', models.CharField(max_length=32, null=True, verbose_name='ICCID号')),
                ('product_num', models.CharField(max_length=32, null=True, verbose_name='货号')),
                ('serial_num', models.CharField(max_length=32, null=True, verbose_name='流水号')),
                ('birthday', models.CharField(max_length=32, null=True, verbose_name='出厂日期')),
                ('dept', models.CharField(max_length=16, null=True, verbose_name='部门')),
                ('create_time', models.DateTimeField(auto_now=True, null=True, verbose_name='添加数据时间')),
                ('spare_1', models.CharField(max_length=128, null=True, verbose_name='备用1')),
                ('spare_2', models.CharField(max_length=128, null=True, verbose_name='备用2')),
            ],
            options={
                'db_table': 'machine',
            },
        ),
    ]
