# Generated by Django 2.0.4 on 2019-09-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='car', verbose_name='保存文件路径')),
            ],
            options={
                'db_table': 'machine_file',
            },
        ),
    ]
