# Generated by Django 2.2.2 on 2019-07-17 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Can',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True, null=True, verbose_name='服务器添加数据时间')),
                ('ter_time', models.DateTimeField(null=True, verbose_name='终端发送时间')),
                ('data', models.CharField(max_length=1024, verbose_name='报文数据')),
                ('type', models.IntegerField(default=0, verbose_name='数据类型')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.Car', verbose_name='对应车辆')),
            ],
            options={
                'db_table': 'can',
            },
        ),
    ]
